### ISSUE TITLE
Nginx pretty url / rewrite isn't working on mac

### ISSUE THREAD

**Issue by pixluser** [xpf0000/PhpWebStudy#48]
Hello,

// I just discovered your fantastic software, because I didn't want to use something like MAMP, or MAMP pro.
// Thank you for it, it's very fast and neat!

The problem I have :
Using urls like /xxxx/xxx with Nginx give me 404 Not Found.
From a fresh install  PhpWebStudy-1.0.46-arm64.dmg (on M1 pro)

I refreshed permalinks in wordpress too, two times. Didn't work for me.
---

Is there a config hack needed?

PS: Cannot use apache too, (basic version and brew version too) : got forbidden on 8080

**Comment by xpf0000** [comment]
I'm glad you enjoyed this software, thanks
1. The accessibility of a site is related to the permissions of the folder where the site is located, and both the owner user and read/write permissions of the folder will affect the accessibility of the site
2. NGINX Rewrite Rules need to be set according to the project, depending on your project. After setting them up, you can open the site's configuration file to view and test them

**Comment by xpf0000** [comment]
1. nginx url rewrite quick settings provided in the site editing interface, just some common project general settings, may be due to project upgrades and other reasons, may not always be completely correct.
2. nginx url rewrite settings in the site editing interface, will be saved to a separate configuration file, in the main configuration file, will load the url rewrite file, site -> setup -> Config File -> nginx, open the site's main configuration file, there is a line, similar to.
include /Users/xxx/Library/PhpWebStudy/server/vhost/rewrite/xxx.conf;
This file is the site's nginx url rewrite configuration file.
3. software will not actively modify the site's nginx url rewrite configuration, unless the user manually set in the site editing interface, or directly modify the nginx url rewrite configuration file

**Comment by pixluser** [comment]
Ooo ! I forgot to setup the quick settings at the bottom of the windows!
It now work directly!

SO cool !

Thank you so much!
