### ISSUE TITLE
Apache Errors

### ISSUE THREAD

**Issue by xcrap** [xpf0000/PhpWebStudy#84]
I have everything working and the websites are displaying well and so but I seen some Apache Errors that seem off, I like to have everything clean maybe you know why this is happening:

[Mon Apr 22 06:49:59.896895 2024] [unixd:alert] [pid 76797] (9)Bad file descriptor: AH02155: getpwuid: couldn't determine user name from uid -1, you probably need to modify the User directive

I got a lot of this errors, not every single time I open pages but every now and then.

**Comment by xpf0000** [comment]
```
[Mon Apr 22 06:49:59.896895 2024] [unixd:alert] [pid 76797] (9)Bad file descriptor: AH02155: getpwuid: couldn't determine user name from uid -1, you probably need to modify the User directive
```

This problem has been fixed in the new version. This is because the apache configuration file does not set User and Group. For newer versions, Apache will automatically set User and Group when it starts.

By the way. The [mpm_prefork:notice] and [core:notice] in the log cannot be ignored. Even if the LogLevel is set to error or higher. At least I haven't found a way to ignore them.  So in the error log, it won't be completely clean.

**Comment by xcrap** [comment]
Yeah I realize you always have some notices, it's all good but I'm comparing with the ones getting from other Apache Installations to see and compare what's expected :) 

The change of setting a user/group name will add a new notice in the start:
[Tue Apr 23 11:17:37.878952 2024] [ssl:warn] [pid 92029] AH01873: Init: Session Cache is not configured [hint: SSLSessionCache]

I'll check what's that later on.

Thanks a lot :)
