### ISSUE TITLE
工具箱能否新增生成随机字符串的工具 

### ISSUE THREAD

**Issue by hellowhwei** [xpf0000/PhpWebStudy#91]
工具箱能否新增生成随机字符串的工具  就是那种类似随机密码随机秘钥的那种

**Comment by AkshatRamanathan** [comment]
@xpf0000 Can i take this up to work on this feature. Good for first issue as a vue beginner right?

**Comment by hellowhwei** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by xpf0000** [comment]
> @xpf0000 Can i take this up to work on this feature. Good for first issue as a vue beginner right?

Yes. This is a good start.  

But this issue is only a string related content.  If only this simple function takes up a toolbar position.  It may be a bit inappropriate 

You may need to consider more string related features For example, MD5 AESDES, etc.  You can think about it first Then share your ideas and discuss them

**Comment by xpf0000** [comment]
The latest version has been added

**Comment by hellowhwei** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
